config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #
  root "cars#index"
  post "/auth/login", to: "authentications#login"
  get "/auth/login/new", to: "authentications#new"


  resources :cars do
    resources :maintenance_car_services, only: [ :new, :create ]
  end

  resources :maintenance_car_services
end

app/models/maintenance_car_service.rb
class MaintenanceCarService < ApplicationRecord
  belongs_to :car

  enum status: { pending: 0, in_progress: 1, completed: 2 }

  validates :description, :date, presence: true
  validates :status, inclusion: { in: MaintenanceCarService.statuses.keys }
end

app/controllers/maintenance_car_services_controller.rb
class MaintenanceCarServicesController < ApplicationController
  before_action :set_maintenance_car_service, only: %i[ show edit update destroy ]
  before_action :set_car, only: [ :new, :create ]
  before_action :set_is_nested_url, only: [ :new, :edit ]
  before_action :set_car_list, only: [ :new, :edit ]


  # GET /maintenance_car_services or /maintenance_car_services.json
  def index
    @maintenance_car_services = MaintenanceCarService.all

    # Filtrar por estado
    if params[:status].present?
      @maintenance_car_services = @maintenance_car_services.where(status: params[:status])
    end

    # Filtrar por número de placa del auto
    if params[:plate_number].present?
      @maintenance_car_services = @maintenance_car_services.joins(:car).where(cars: { plate_number: params[:plate_number] })
    end
  end

  # GET /maintenance_car_services/1 or /maintenance_car_services/1.json
  def show
  end

  # GET /maintenance_car_services/new
  def new
    if @car
      @maintenance_car_service = MaintenanceCarService.new(car: @car)
    else
      # Si no hay car_id, simplemente creamos el servicio de mantenimiento sin asociarlo a un carro
      @maintenance_car_service = MaintenanceCarService.new
    end
  end

  # GET /maintenance_car_services/1/edit
  def edit
  end

  # POST /maintenance_car_services or /maintenance_car_services.json
  def create
    if @car
      @maintenance_car_service = MaintenanceCarService.new(maintenance_car_service_params.merge(car_id: @car.id))
    else
      @maintenance_car_service = MaintenanceCarService.new(maintenance_car_service_params)
    end

    respond_to do |format|
      if @maintenance_car_service.save
        format.html { redirect_to @maintenance_car_service, notice: "Maintenance car service was successfully created." }
        format.json { render :show, status: :created, location: @maintenance_car_service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_car_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_car_services/1 or /maintenance_car_services/1.json
  def update
    puts @maintenance_car_service.inspect
    respond_to do |format|
      if @maintenance_car_service.update(maintenance_car_service_params)
        format.html { redirect_to @maintenance_car_service, notice: "Maintenance car service was successfully updated." }
        format.json { render :show, status: :ok, location: @maintenance_car_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_car_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_car_services/1 or /maintenance_car_services/1.json
  def destroy
    @maintenance_car_service.destroy!

    respond_to do |format|
      format.html { redirect_to maintenance_car_services_path, status: :see_other, notice: "Maintenance car service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_car_service
      @maintenance_car_service = MaintenanceCarService.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_car_service_params
      params.require(:maintenance_car_service).permit(:description, :date, :status, :car_id)
    end

    def set_car
      if params[:car_id].present?
        @car = Car.find(params[:car_id])
      end
    end

    def set_is_nested_url
      @is_nested_url = request.path.include?("/cars/")
    end

    def set_car_list
      @car_list = Car.all.pluck(:id)
    end
end

app/helpers/maintenance_car_services_helper.rb
module MaintenanceCarServicesHelper
end

app/views/maintenance_car_services/_card_maintenance_car_service.html.erb
<div id="<%= dom_id maintenance_car_service %>">
    <div class="p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 my-3">
        <p class="font-bold text-gray-950">Description: <%= maintenance_car_service.description %></p>
        <p class="font-bold text-gray-950">Status: <%= maintenance_car_service.status %></p>
        <p class="font-bold text-gray-950">Discharge date: <%= maintenance_car_service.date %></p>
    </div>
</div>

app/views/maintenance_car_services/_form.html.erb
<%= form_with(model: [@car, @maintenance_car_service],  url: (@car ? car_maintenance_car_services_path(@car) : maintenance_car_services_path), class: "contents") do |form| %>
  <% if maintenance_car_service.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(maintenance_car_service.errors.count, "error") %> prohibited this maintenance_car_service from being saved:</h2>

      <ul>
        <% maintenance_car_service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex-col">
    <div>
      <%= form.label :descripcion_label, "Agrega la descripcion del servicio"%>
      <%= form.text_area :description, rows: 5, class: "w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>
    <div>
      <%= form.label :date_label, "Fecha en que se realizo"%>
      <%= form.date_field :date %>
    </div>

    <div>
      <%= form.label :date_label, "Estado actual"%>
      <%= form.select :status, 
                options_for_select(MaintenanceCarService.statuses.keys.map { |key| [key.humanize, key] }, form.object.status), 
                {}, 
                class: "border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    
    <% unless @is_nested_url %>
      <div>
        <%= form.label :car_list_label, "Vehiculo a asignar"%>
        <%= form.select :car_id, 
                  options_for_select(@car_list.presence || []), 
                  {}, 
                  class: "border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
      </div>
    <% end %>
  </div>
  <%= form.submit class: "my-4 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
<% end %>

app/views/maintenance_car_services/_form_edit.html.erb
<%= form_with(model: @maintenance_car_service, class: "contents") do |form| %>
  <% if maintenance_car_service.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(maintenance_car_service.errors.count, "error") %> prohibited this maintenance_car_service from being saved:</h2>

      <ul>
        <% maintenance_car_service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex-col">
    <div>
      <%= form.label :descripcion_label, "Agrega la descripcion del servicio"%>
      <%= form.text_area :description, rows: 5, class: "w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>
    <div>
      <%= form.label :date_label, "Fecha en que se realizo"%>
      <%= form.date_field :date %>
    </div>

    <div>
      <%= form.label :date_label, "Estado actual"%>
      <%= form.select :status, 
                options_for_select(MaintenanceCarService.statuses.keys.map { |key| [key.humanize, key] }, form.object.status), 
                {}, 
                class: "border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    
    <% unless @is_nested_url %>
      <div>
        <%= form.label :car_list_label, "Vehiculo a asignar"%>
        <%= form.select :car_id, 
                  options_for_select(@car_list.presence || []), 
                  {}, 
                  class: "border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
      </div>
    <% end %>
  </div>
  <%= form.submit class: "my-4 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
<% end %>

app/views/maintenance_car_services/_maintenance_car_service.html.erb
<div id="<%= dom_id maintenance_car_service %>">
    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <%= maintenance_car_service.car_id%>
        </th>
        <td class="px-6 py-4">
            <%= maintenance_car_service.description%>
        </td>
        <td class="px-6 py-4">
            <%= maintenance_car_service.status%>
        </td>
        <td class="px-6 py-4">
            <%= maintenance_car_service.date%>
        </td>
        <td class="px-6 py-4 text-white">
            <%= link_to "Ver", maintenance_car_service, class: "ml-2 rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium" %>
        </td>
    </tr>
</div>

app/views/maintenance_car_services/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing maintenance car service</h1>

  <%= render "form_edit", maintenance_car_service: @maintenance_car_service %>

  <%= link_to "Show this maintenance car service", @maintenance_car_service, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to maintenance car services", maintenance_car_services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/maintenance_car_services/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Maintenance car services" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lista de Servicios</h1>
    <%= link_to "Agregar mantenimiento", new_maintenance_car_service_path, class: "rounded-lg py-3 px-5 bg-green-600 text-white block font-medium" %>
  </div>

  <div class="mb-4">
    <%= form_with url: maintenance_car_services_path, method: :get, local: true, class: "flex gap-3" do |form| %>
      <div>
        <%= form.label :status, "Filtrar por estado", class: "block mb-2" %>
        <%= form.select :status, options_for_select(MaintenanceCarService.statuses.keys.map { |s| [s.titleize, s] }, params[:status]), prompt: "Seleccione un estado", class: "border rounded-lg px-3 py-2" %>
      </div>
      <div>
        <%= form.label :plate_number, "Buscar por placa", class: "block mb-2" %>
        <%= form.text_field :plate_number, value: params[:plate_number], placeholder: "Número de placa", class: "border rounded-lg px-3 py-2" %>
      </div>
      <div class="mt-8">
        <%= form.submit "Filtrar", class: "bg-blue-500 text-white rounded-md px-4 py-2 hover:bg-blue-400" %>
      </div>

      <div class="mt-10">
        <%= link_to "Limpiar", maintenance_car_services_path, class: "px-5 py-2 bg-red-500 text-white rounded-md" %>
      </div>
    <% end %>
  </div>


  <div class="relative overflow-x-auto my-4">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
            <th scope="col" class="px-6 py-3">
                Car ID
            </th>
            <th scope="col" class="px-6 py-3">
                Descripcion
            </th>
            <th scope="col" class="px-6 py-3">
                Estado
            </th>
            <th scope="col" class="px-6 py-3">
                Fecha
            </th>
            <th scope="col" class="px-6 py-3">
                
            </th>
        </tr>
      </thead>
      <tbody>
        <% @maintenance_car_services.each do |maintenance_car_service| %>
          <%= render maintenance_car_service %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/maintenance_car_services/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New maintenance car service</h1>

  <%= render "form", maintenance_car_service: @maintenance_car_service %>

  <%= link_to "Back to maintenance car services", maintenance_car_services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/maintenance_car_services/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "card_maintenance_car_service", maintenance_car_service: @maintenance_car_service %>

    <%= link_to "Edit this maintenance car service", edit_maintenance_car_service_path(@maintenance_car_service), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to maintenance car services", maintenance_car_services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this maintenance car service", @maintenance_car_service, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>