config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #
  root "cars#index"
  post "/auth/login", to: "authentications#login"
  get "/auth/login/new", to: "authentications#new"


  resources :cars do
    resources :maintenance_car_services, only: [ :new, :create ]
  end

  resources :maintenance_car_services
end

app/models/car.rb
class Car < ApplicationRecord
    validates :plate_number, uniqueness: true
    validates :year, numericality: {
        only_integer: true,
        in: 1900..Time.zone.now.year,
        message: "must be between 1900 and #{Time.zone.now.year}"
    }
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
    @car_maintenance_services = MaintenanceCarService.where(car_id: @car)
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy!

    respond_to do |format|
      format.html { redirect_to cars_path, status: :see_other, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:plate_number, :model, :year)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>" class="p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100">
    <p class="font-bold text-gray-950">Plate Number: <%= car.plate_number %></p>
    <p class="font-bold text-gray-950">Model: <%= car.model %></p>
    <p class="font-bold text-gray-950">Year: <%= car.year %></p>
    
    <% unless action_name == 'show' %>
        <button class="bg-blue-500 text-white rounded-md mt-2 px-2">
        <%= link_to "Show this car", car %>
        </button>
    <% end %>
</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex-col">
    <div>
      <%= form.label :plate_label, "Agrega la Placa"%>
      <%= form.text_field :plate_number,class: "w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>
    <div>
      <%= form.label :model_label, "Modelo del vehiculo"%>
      <%= form.text_field :model, class: "w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <div>
      <%= form.label :year_label, "Año"%>
      <%= form.number_field :year, class: "w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>
  </div>
  <%= form.submit class: "my-4 rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer"%>
<% end %>

app/views/cars/edit.html.erb
<% content_for :title, "Editing car" %>

<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Cars" %>

<div class="flex-col">
  <h1 class="font-bold text-xl m-2">Cars List</h1>

  <div id="cars" class="grid grid-cols-3 gap-2">
    <% @cars.each do |car| %>
      <%= render car %>
    <% end %>
    
    <div class="flex justify-center items-center">
      <button class="bg-green-400 text-white rounded-md mt-2 px-2">
        <%= link_to "Add New car", new_car_path %>
      </button>
    </div>
</div>
<%= link_to "Ver todos los servicios", maintenance_car_services_path , class: "ml-2 rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium" %>

app/views/cars/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Car</h1>

  <%= render "form", car: @car %>

  <%= link_to "Back to Cars", cars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-xl font-bold mt-3">Informacion vehiculo:</h1>
<%= render @car %>

  <%= link_to "Edit this car", edit_car_path(@car), class: "mt-2 rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium" %>
  <%= link_to "Back cars", cars_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-400 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy car", @car, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 font-medium" %>
  </div>

<div>
  <h1 class="text-xl font-bold mt-3">Servicios:</h1>
  
  <div class="grid grid-cols-3 gap-2">
    <% @car_maintenance_services.each do |service| %>
      <div class="p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 my-3">
        <p class="font-bold text-gray-950">Description: <%= service.description %></p>
        <p class="font-bold text-gray-950">Status: <%= service.status %></p>
        <p class="font-bold text-gray-950">Discharge date: <%= service.date %></p>
      
      </div>
    <% end %>
    <button class="bg-green-400 text-white rounded-md mt-2 px-2">
        <%= link_to "Add Service", new_car_maintenance_car_service_path(@car) %>
    </button>
  </div>
  
</div>